import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import MouseMoveEffect from "@/components/ui/mouseEffect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen bg-[#f0faff] flex flex-col">
          <MouseMoveEffect />
          <div className=" z-0 fixed inset-0">
            <div className="absolute inset-0 bg-[#f0faff] " />
            <div className="absolute right-0 top-0 h-[500px] w-[500px] bg-purple-500/30 blur-[100px]" />
            <div className="absolute bottom-0 left-0 h-[500px] w-[500px] bg-[#ceefce] blur-[100px]" />
          </div>
          <Navbar/>
            <main className="flex z-0 items-center justify-center">{children}</main>
            <div className="relative z-10">
              <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
