import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import MouseMoveEffect from "@/components/ui/mouseEffect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative z-10 min-h-screen flex flex-col">
        <MouseMoveEffect />
      <div className=" z-0 fixed inset-0">
        <div className="absolute z-0 inset-0 bg-gradient-to-b from-background via-background/90 to-background" />
        <div className="absolute z-0 right-0 top-0 h-[500px] w-[500px] bg-blue-500/10 blur-[100px]" />
        <div className="absolute z-0 bottom-0 left-0 h-[500px] w-[500px] bg-purple-500/10 blur-[100px]" />
      </div>
        <Navbar/>
          <main className="flex-1">{children}</main>
          <div className="relative z-20">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
